version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: giorgi123
      POSTGRES_DB: cinema_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .                   
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:giorgi123@db:5432/cinema_booking
      JWT_SECRET: your-secret-key
      PORT: 5000
    volumes:
      - ./backend:/app
      - ./shared:/app/shared       

volumes:
  postgres-data:
